name: ${project.artifactId}
version: ${project.version}
main: io.github.kpgtb.kkcore.KKcore
authors: [ KPG-TB ]
description: Core of KK minecraft plugins by KPG-TB
website: kpgtb.github.io
softdepend:
  - PlaceholderAPI